#pragma once

namespace nutsloop::claude_impl::chelp {

// MARK (CLAUDE_HELP) HELP OPTION constexpr variables.
static constexpr auto HELP_NAME_ = "--HELP OPTION\n\n";
static constexpr auto HELP_ =
    "SYNOPSIS\n"
    "  long form:\n"
    "    --help\n"
    "    --help=<option-name>\n"
    "  short form:\n"
    "    --?\n"
    "    --?<option-name>\n"
    "    --?=<option-name>\n"
    "\n"
    "DESCRIPTION\n"
    "  Display help information for claude-impl CLI tool.\n"
    "  - If no option name is specified, displays general help with all options.\n"
    "  - If an option name is specified, displays detailed help for that option.\n"
    "  - Omit the `--`/`-` prefix from the option name.\n"
    "\n"
    "AVAILABLE OPTIONS\n"
    "  Model Configuration:\n"
    "    --model             Select AI model to use\n"
    "    --temperature       Set generation randomness (0.0-2.0)\n"
    "    --max-tokens        Maximum tokens to generate\n"
    "    --top-p             Nucleus sampling parameter (0.0-1.0)\n"
    "    --top-k             Top-k sampling parameter\n"
    "    --context-window    Context window size\n"
    "\n"
    "  Streaming & Output:\n"
    "    --stream            Enable response streaming\n"
    "    --output-format     Output format (json, text, markdown, xml)\n"
    "    --output-dir        Directory for output files\n"
    "\n"
    "  API Configuration:\n"
    "    --api-key           Anthropic API key\n"
    "    --endpoint          API endpoint URL\n"
    "    --timeout           Request timeout in seconds\n"
    "    --retry-count       Number of retry attempts\n"
    "\n"
    "  Behavior Flags:\n"
    "    --verbose           Enable verbose output\n"
    "    --dry-run           Simulate without making API calls\n"
    "    --disable-safety    Disable safety checks (caution!)\n"
    "    --enable-cache      Enable response caching\n"
    "    --disable-cache     Disable response caching\n"
    "\n"
    "  File Options:\n"
    "    --config-file       Path to configuration file\n"
    "    --input-file        Path to input file with prompts\n"
    "    --log-file          Path for log output\n"
    "    --log-level         Log verbosity (debug, info, warn, error, none)\n"
    "\n"
    "  System:\n"
    "    --system-prompt     System prompt for the model\n"
    "    --version           Display version information\n"
    "    --help              Display this help\n"
    "\n"
    "EXAMPLES\n"
    "  claude-impl --help                    # Display this help\n"
    "  claude-impl --help=model              # Help for --model option\n"
    "  claude-impl --?temperature            # Help for --temperature option\n";

} // namespace nutsloop::claude_impl::chelp
